domain: "rikkynguyen.github.io"
url: "https://rikkynguyen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Rikky Nguyen" # the name of your site, e.g. ACME Corp.

sass:
  sass_dir: _sass
  load_paths:
  - _sass
  - /bundle/ruby/3.0.0/gems/bootstrap-5.1.3/assets/stylesheets

include:
  - _pages
  - .htaccess
# theme: jekyll-theme-cayman